# The GroupName here is used to identify your company or business unit that
# created this webhook.
# For example, this may be "acme.mycompany.com".
# This name will need to be referenced in each Issuer's `webhook` stanza to
# inform cert-manager of where to send ChallengePayload resources in order to
# solve the DNS01 challenge.
# This group name should be **unique**, hence using your own company's domain
# here is recommended.
groupName: acme.stadtmueller.at

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: vstadtmueller/cert-manager-webhook-powerdns
  tag: main
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

secretName:
  - pdns-secret

# enable the use of Pod Security Policies (PSPs)
# either set `create` to true in order to create a new PSP with minimal persmissions 
# or leave set to false and add a list of PSP names to `use` for the inclusion of existing
# PSPs
podSecurityPolicy:
  # set to true to enable
  enable: false
  create: false
  use: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# set the security context of the webhook pod
podSecurityContext: {}
#  runAsUser: 1000
#  runAsGroup: 3000
#  fsGroup: 2000

# set the security context of the container started in the webhook
securityContext: {}
#  runAsUser: 1000
#  runAsGroup: 3000
#  fsGroup: 2000



